# Generated by Django 5.0.6 on 2026-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('areas', models.TextField(help_text='Comma-separated list of areas')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_time', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shops/banners/')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
