# Generated by Django 5.0.6 on 2026-07-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payments/proofs/')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Verification'), ('received', 'Payment Received'), ('rejected', 'Payment Rejected'), ('refunded', 'Refunded')], default='waiting', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
