# Generated by Django 5.0.6 on 2026-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_shops',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for platform-wide coupon', related_name='coupons', to='shops.shop'),
        ),
    ]
